const QUESTIONS_COUNT = 3
const MIN_RANDOM = 1
const MAX_RANDOM = 100
const MAX_RANDOM_CALC = 9
const MIN_PROGRESSION_STEP = 1
const MAX_PROGRESSION_STEP = 10
const MIN_PROGRESSION_EL_COUNT = 5
const MAX_PROGRESSION_EL_COUNT = 10

export { QUESTIONS_COUNT, MIN_RANDOM, MAX_RANDOM, MAX_RANDOM_CALC, MIN_PROGRESSION_STEP, MAX_PROGRESSION_STEP, MIN_PROGRESSION_EL_COUNT, MAX_PROGRESSION_EL_COUNT }
